#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_runtime_3d_tools = env_modules.Clone()
env_runtime_3d_tools.add_source_files(env.modules_sources, "*.cpp")
